### ISSUE TITLE
双向控制demo有点问题

### ISSUE THREAD

**Issue by lceric** [loo41/Omi-Swiper#2]
双向控制demo有点问题

**Comment by loo41** [comment]
多谢，看了一下，[code](https://github.com/loo41/Omi-Swiper/blob/master/example/src/elements/comonents/thumbs.js)，配置的时候加loop造成的，去掉就没问题了, 更多的配置你需要去看文档 [文档](https://www.swiper.com.cn/api/thumbs/2018/0916/433.html)
